name: DuckHunt CI

on: 
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: CloneCode
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install DEpendencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: RunTests
        run: pytest

      - name: Linter
        run: flake8 .
      